### ISSUE TITLE
Window size way too large

### ISSUE THREAD

**Issue by valeth** [iced-rs/iced#1028]
For some reason the default window size stretches all the way over to my second monitor.
Trying to pass window settings like `size` or `max_size` don't seem to have any effect.

I cannot remember it doing this in earlier versions, so it might just be a recent regression.

Shown here with the todo example application on the master branch (589f68df).
![Screenshot_20210906_211656](https://user-images.githubusercontent.com/3198362/132255242-045a87bb-5081-43be-9d22-ec7cb8eee75f.png)

System:
OS: Arch Linux 64bit
CPU: AMD FX-8350
GPU: AMD Radeon RX480

**Comment by valeth** [comment]
One thing I noticed is that forcing 96 DPI in KDE settings seems to produce a reasonably scaled window.
So most likely something changed in the way X11 reports scaling that broke this.

**Comment by hecrj** [comment]
Could you try if the `winit` examples have the same issue? In that case, we should report the issue there!

I'm closing this since it seems very likely to be an issue in `winit`, or maybe related to your specific environment. Feel free to reopen if you find any evidence that `iced` may be at fault here!
