### ISSUE TITLE
Software renderer

### ISSUE THREAD

**Issue by edouardparis** [iced-rs/iced#1071]
This issue is to measure interest and demonstrate support for the development of a software renderer for Iced

As described in the [roadmap](https://github.com/iced-rs/iced/blob/93fec8d273ef8305e1c2456abe0c8ecd7a9d9407/ROADMAP.md#reuse-existing-2d-renderers), two choices may be considered:
- [ ] [`skia`](https://skia.org), existing issue: https://github.com/iced-rs/iced/issues/520
- [ ] [`piet`](https://github.com/linebender/piet)

**Comment by gonsor** [comment]
Very interested in a 2d renderer. Would prefer piet as it is a rather lean dependency compared to the monstrous skia. I fear that the systems that have no 3d acceleration have a big overlap with the systems that skia does not compile on. ;)

If I see this correctly, @hecrj already wrote some [glue code](https://github.com/hecrj/piet-window) to combine winit with piet. Has the iced / piet approach ever been evaluated?

**Comment by hecrj** [comment]
@gonsor Yes! I'm actively working towards an `iced_piet` renderer.

`piet-window` was an experiment and posed a bunch of challenges. Instead of using `winit`, the plan is to build an `iced` runtime on top of `druid-shell`.

The work in #1110 set the foundations to make this road easier. We are getting there!

**Comment by darosior** [comment]
Hello there. A friendly ping to learn what's the status of this, given It's been a year since the last comment. It would be very useful for downstream applications to not require their users to have 3D libraries.

**Comment by hecrj** [comment]
This will land soon, together with the work from #1697.

In the end, I chose [`tiny-skia`](https://github.com/RazrFalcon/tiny-skia) since it seems it's the best viable option and we already depend on it for SVG rendering!

Work is happening in the [`feature/software-renderer`](https://github.com/iced-rs/iced/tree/feature/software-renderer) branch.
