### ISSUE TITLE
Make ColoredVertex2D (and similar structs) use Point and Color for the fields position and color, repectively

### ISSUE THREAD

**Issue by AndersonDeMatos** [iced-rs/iced#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Currently, the struct ColoredVexter2D expects an array of 2 elements of the type f32 for position (x and y) and an array of 4 elements of the type f32 for color (r, g, b and a). 

### What is the expected behavior?

I'm following the example project 'geometry', trying to create color wheel widget. In the example, the values for position ans color for the ColoredVertex2Ds are hardcoded, but in the widget I want to make, I would need to do that programmatically, using an iterator from 0 to 360 to create the positions and colors for the vertexes for the hue ring. For that I would need to use hsla or hsva color type, which currently are not implemented for Color.  I could create a function to convert hsla or hsva values and return a [f32; 4]  with the rgba values to use it the the color field of the ColoredVertex2D, but if it expected a Color instead, I could implement those functions directly for the Color struct and return a new Color.

### Version

master

### Operative System

Linux

### Do you have any log output?

```shell
It's not a bug, only an area that could be improved, in my opinion.
```

**Comment by hecrj** [comment]
`Color` represents a color in the sRGB color space, while the `f32` values in `ColoredVertex2D` represent a color in linear RGB. Furthermore, `ColoredVertex2D` needs to consist of final data because it is directly uploaded to GPU memory as-is.

I recommend you to enable the `palette` feature which will allow you to leverage colors in the `palette` crate and easily convert them to `Color` in `iced`. Then, you should use `Color::into_linear` to get the `f32` linear values.
