### ISSUE TITLE
Rust analyzer not showing functions in the column![] macro

### ISSUE THREAD

**Issue by Luxvao** [iced-rs/iced#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

So I tried creating a new iced app (I'm new so I really need code completion), but I've noticed that if you put let's say a button widget into the `column![]` macro like so:
```
column![
    button("+")
]
```
it won't suggest any functions to call on the button like `on_press`. So if I start typing `.on_press()` it won't suggest anything. Is this a problem with rust analyzer (in vs code and neovim)

### What is the expected behavior?

It would suggest me functions and other stuff

### Version

master

### Operative System

Windows

**Comment by tarkah** [comment]
This is a known issue due to the collision with the builtin rust macro `column!`.

Rust analyzer isn't smart enough to properly shadow the built-in macro when importing the iced macro, so it doesn't properly resolve completions, etc for it.

As a workaround you can `import iced::widget::column as col` and use `col!`.

I'm not sure if anyone's opened a ticket upstream yet, but ideally this gets fixed in RA so this all works as expected.

**Comment by Luxvao** [comment]
The solution worked. Thanks!
