### ISSUE TITLE
Integration example font display bug

### ISSUE THREAD

**Issue by godcodehunter** [iced-rs/iced#1900]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I tried to run the integration example, but the fonts seem to be broken
![image](https://github.com/iced-rs/iced/assets/22272886/0cee1ae5-346a-49d8-9f15-6394fc4f82a6)

### What is the expected behavior?

Fonts must display correctly

### Version

master

### Operative System

Linux

**Comment by kaimast** [comment]
Does this only happen on web for you? It seems like there is support for wasm in cosmic-text (see [here](https://github.com/pop-os/cosmic-text/pull/121)) but maybe something is missing on iced's side.

**Comment by godcodehunter** [comment]
Yep, only web, native run as expected

**Comment by genusistimelord** [comment]
ok So the reason why text is not rendering is due to no fonts getting loaded at all for wasm. Im guessing this is due to some sort of WASM restriction not entirely sure yet. Maybe @jackpot51 might now this answer. Anyways To fix the issue I simply Imported a Font into the system from included Bytes. 

You can see the entire source here: https://pastebin.com/0CKyxQcz

@martinhalford this might also fix your web asm issues too. this is a temporary fix till we figure out who no fonts are loading for web asm though.

**Comment by martinhalford** [comment]
That's awesome @genusistimelord !! Thank you! I'll take a look at your code and try it out. Much appreciated!

**Comment by genusistimelord** [comment]
you also might also need to add 

cosmic-text = { version = "0.9.0", features = ["wasm-web"]}
to your cargo.toml

**Comment by martinhalford** [comment]
@genusistimelord - Thanks again for the code. 

Apologies if I'm still too much of a newbie to really understand what is going on here.

I'm just trying to get the latest Iced-rs example Todos app to work, before I start messing around with my own code:
[Todos main.rs](https://github.com/iced-rs/iced/blob/master/examples/todos/src/main.rs)

Your code uses a canvas and an event loop, and you create a renderer.  You then load the font directly into that renderer - which is fine.

```
pub const ARIAL_FONT_BYTES: &[u8] = include_bytes!("../arial.ttf");
   ...
renderer.load_font(Cow::from(ARIAL_FONT_BYTES));
```

The Todos example code doesn't seem to use a renderer (at least not directly).  Instead, it is (trying) to load the font as bytes within the Application constructor. 

```
    fn new(_flags: ()) -> (Todos, Command<Message>) {
        (
            Todos::Loading,
            Command::batch(vec![
                font::load(include_bytes!("../fonts/icons.ttf").as_slice())
                    .map(Message::FontLoaded),
                Command::perform(SavedState::load(), Message::Loaded),
            ]),
        )
    }
```
I'm not sure how to inject a renderer into this code in a similar way to your event loop driven code.

What would you recommend I do to this Todos sample code in order to force it to load the font properly?

Thanks again for your help!

**Comment by genusistimelord** [comment]
yeah for that you will need to use the Command font loader https://github.com/iced-rs/iced_aw/blob/main/examples/number_input/src/main.rs#L52  this will require you to use Application as sandbox has no way to load external fonts atm.
