### ISSUE TITLE
feature request - mac system menu support

### ISSUE THREAD

**Issue by pm100** [iced-rs/iced#2292]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

see https://github.com/iced-rs/iced_aw/issues/211 

### What is the expected behavior?

n/a

### Version

master

### Operating System

macOS

### Do you have any log output?

```shell
n/a
```

**Comment by pm100** [comment]
I hope feature requests can be filed here, the template seems to not want it

**Comment by hecrj** [comment]
The template does indeed not want it because this is a bug tracker.

New features can be discussed either in our Discord server or our Discourse forum:

![image](https://github.com/iced-rs/iced/assets/518289/97520bc9-0c56-466d-82ce-39b6445b99b9)

In any case, system menus are a part of [our roadmap](https://whimsical.com/roadmap-iced-7vhq6R35Lp3TmYH4WeYwLM) already.
