### ISSUE TITLE
GUI freezes upon interacting with a widget under Wayland

### ISSUE THREAD

**Issue by Dirleye** [iced-rs/iced#2297]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Moving the cursor over a widget freezes the application, which I then have to manually close.
This is a desktop application using default settings other than a custom window size, though the example programs behave the same way.
I'm using an Nvidia GPU with the latest drivers. Setting `std::env::set_var("WINIT_UNIX_BACKEND", "x11");` to force XWayland worked with Iced 0.10, but now has no effect.

I would appreciate guidance on where to look to find the route of this issue.
Thank you.

### What is the expected behavior?

Application runs without freezes.

### Version

crates.io release

### Operating System

Linux

**Comment by GenericConfluent** [comment]
I ran into this earlier today, also being on Wayland with NVIDIA. I decided to do some debugging and this is not an issue with `iced`, it's a `winit` problem. Which I confirmed by writing a short test exec with `winit` and `wgpu` (I tested with both Hyprland and river). 

It seems to be related to the `CursorLeft` event but I don't know why (except it's not like the `iced` apps work as long as the cursor is in the window when it starts, `iced` is frozen from the beginning). Stuff seems to work fine so long as the cursor is sitting within the bounds of the window, after that the event loop freezes and you can't close the window normally (make sense since not event processing is happening).  The issue may have come as a result of [EventLoop 3.0 Changes](https://github.com/rust-windowing/winit/issues/2900) but that's just a guess on my part, since my experience with `winit` is limited.

It also doesn't look like there is an issue open for this yet.

**Comment by GenericConfluent** [comment]
This can be fixed by moving to a more recent commit of `winit`. The `crates.io` version is insufficient.

**Comment by blueOkiris** [comment]
Neither updating winit nor wgpu is working for me

**Comment by ids1024** [comment]
Are you on the 550.67 driver that was released a couple days ago, or an earlier 550 driver?

https://www.nvidia.co.uk/download/driverResults.aspx/223635/en-us mentions "Fixed a bug that caused wgpu applications to hang on Wayland".

**Comment by blueOkiris** [comment]
Ah that's probably it. I update to 550, but only 550.54. I'll see if I can get the latest on my distro (NixOS)

**Comment by Dirleye** [comment]
This is indeed fixed with the 550.67 driver for me.
@blueOkiris if it's working well for you too I'll close?

**Comment by Dirleye** [comment]
I'll assume it's all good now, thanks for the help everyone.
