### ISSUE TITLE
custom command feature missing in 0.13

### ISSUE THREAD

**Issue by Decodetalkers** [iced-rs/iced#2543]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

In month, I make a pr in https://github.com/iced-rs/iced/pull/2146/. This pr allow to add extra action passed to iced, it is merged, and we develop https://github.com/waycrate/exwlshelleventloop this project. but now I find this feature is missing in new iced.. 

### What is the expected behavior?

Can you help keep the  feature? it is important to our program

### Version

master

### Operating System

macOS

**Comment by Decodetalkers** [comment]
I find the structure of iced is changed, not it cannot simply add a Box<dyn Any> into actions..

**Comment by Decodetalkers** [comment]
Ok.. maybe I can use Output<T>, and Strict T to have try_into() trait.. can be try_into my custom actions

**Comment by jdbosser** [comment]
Regarding the breaking changes: I think this is to be expected with software that is still in active development. The maintainers of iced have warned us at several instances that breaking changes are likely. 

I, for one, do _want_ breaking changes at this moment in time, since this allows the maintainers to experiment and to find an api that makes sense. It is better for the project in the long run. 

To help you out, while I have no experience working with `Commands`, I think that the struct you are looking for is now located at `iced::Task`.

**Comment by DaRacci** [comment]
It would be a good idea to start including breaking changes in the change-logs like renaming of Command to Task.

**Comment by Decodetalkers** [comment]
Ok , this is not a problem for me anymore.. ok, I will close this issue
