### ISSUE TITLE
Crashing on wayland

### ISSUE THREAD

**Issue by Zuzuk-null** [iced-rs/iced#722]
i export variable `WINIT_UNIX_BACKEND=wayland`, run [counter example](https://github.com/hecrj/iced/tree/master/examples/counter) and get runtime error: [Output and backtrace](https://pastebin.com/N032qT8w)

**Comment by 13r0ck** [comment]
Does this help?
https://github.com/hecrj/iced/issues/333

**Comment by Zuzuk-null** [comment]
> Does this help?
> [# 333](https://github.com/hecrj/iced/issues/333)
No. Application run with xwayland

**Comment by Zuzuk-null** [comment]
I think the problem is in winit, and if I try to replace winit with sdl2, then I can run the application with wayland

**Comment by hecrj** [comment]
@Zuzuk-null How are you switching `winit` with `sdl2`? Is there an SDL2 shell I am not aware of?

**Comment by unrelentingtech** [comment]
Looks like you are using software rendering (lavapipe). I can reproduce by manually selecting lavapipe instead of radeon (RADV):

```sh
VK_ICD_FILENAMES=/usr/local/share/vulkan/icd.d/lvp_icd.x86_64.json target/debug/pane_grid
```

Seems like lavapipe wayland integration is just not complete, as the same error happens with [vkcube](https://github.com/KhronosGroup/Vulkan-Tools/tree/master/cube). And you are probably using SDL2 apps through Xwayland, if you don't have `SDL_VIDEODRIVER=wayland` set.

What GPU do you have? If it's quite old, you might really have no Vulkan support. Otherwise, you might need to install the driver, e.g. on Arch they are packaged separately as `vulkan-radeon` and `vulkan-intel`.
