### ISSUE TITLE
Target OS requirements for apps

### ISSUE THREAD

**Issue by sourcebox** [iced-rs/iced#780]
Is there any information about the system requirements on Windows and macOS? I saw that the Cryptowatch Deskto‪p is listed in the Mac App Store as macOS 10.11 or later. Does it also work on 10.15 and Big Sur?

**Comment by kekcheburec** [comment]
@sourcebox Hey! Most likely the system requirements of Cryptowatch Desktop are based on the version of the toolkit it was compiled on (for example, the macOS SDK). The Iced library is easily cross-compiled for Windows, macOS, Linux. The only system requirement for me is the presence of a graphics card (or built-in) that supports Vulkan (since wgpu mainly relies on it)

**Comment by sourcebox** [comment]
Thanks for the info. I already found out how to build my app on macOS 10.13 with the ability to run it on macOS 10.11. I think that there is a lack of good documentation on this topic generally - this is not related to iced.

While doing this, I discovered that on macOS 10.11 my app and also all iced examples work but crash on exit. This is likely caused by an underlying framework. I used the glow feature for all my tests, this seems to be the only option for older macs.

**Comment by hecrj** [comment]
@sourcebox If you want to see a proper example, [our `build` workflow](https://github.com/hecrj/iced/blob/master/.github/workflows/build.yml) leverages GitHub CI to build the `todos` example and upload the resulting binaries for Windows, macOS, and Linux.
