### ISSUE TITLE
UI only refreshed when I move the mouse cursor

### ISSUE THREAD

**Issue by cbeust** [iced-rs/iced#792]
[Windows 10]

All the examples I've run (including the tour) have the same glitch: the UI only refreshes after I've moved the mouse.

For example, the `Counter` example: I click the "Increment" button, nothing happens, I move the mouse just a tiny bit, and the counter updates to "2".

I can include a video if needed, in case I'm the only one experiencing this.

**Comment by hecrj** [comment]
Does it still happen if you enable the `glow` feature?

**Comment by menoua** [comment]
Has the source of this problem been identified or is there a workaround for it? I have this exact issue on macOS in two applications that I've wrote using Iced. I can't use glow since to my understanding it doesn't support a bunch of the elements I use like Image and Svg.

When it happens is very unpredictable. Originally, it only happened once a minute, but since in big chunks of my app the user shouldn't be using the mouse, they will have no idea that the screen should actually be showing something else, which is a big deal.

Then I decided to send a delayed (+30ms) refresh Command to update after every UI change to trigger a second refresh (basically, 2 refreshes after each UI-changing update instead of 1), but the problem still happens sometimes once every few minutes.

P.S. The mouse movement doesn't trigger an update call, so the problem should be somewhere else. But for the sake of completeness, I have verified that the update call is in fact changing the state and the view call runs without an error (I've set it to panic if an error occurs).
