### ISSUE TITLE
Invisible text in svgs after updating to 0.3.0

### ISSUE THREAD

**Issue by PotatoSquid** [iced-rs/iced#870]
An svg in iced 0.2.0:

![svg in iced 0 2 0](https://user-images.githubusercontent.com/71445090/117428598-c0473c00-af15-11eb-9f41-19405d94769c.png)

The same svg in iced 0.3.0:

![svg in iced 0 3 0](https://user-images.githubusercontent.com/71445090/117428680-d05f1b80-af15-11eb-8301-902576aa4acc.png)

Code:

[iced_svg_test.zip](https://github.com/hecrj/iced/files/6441193/iced_svg_test.zip)

**Comment by hecrj** [comment]
I think this is caused by [`resvg`](https://github.com/RazrFalcon/resvg) switching its renderer to [`tiny-skia`](https://github.com/RazrFalcon/tiny-skia), which does not support text (yet?).

**Comment by ripytide** [comment]
@hecrj Is it intended behavior for the iced SVG widget to not render text? If so would you be open to a PR to amend the documentation to make this explicit?

**Comment by alec-deason** [comment]
I believe this is happening because resvg needs the convert_text method to be called on trees before they are rendered. But that requires a fontdb::Database loaded with fonts. I have a draft PR up (#1908) that shows doing that by naively loading all system fonts, the same way resvg's command line tool does it. And that works for my test case but it seems like the wrong approach given that iced already has a text system with a fontdb::Database in the iced_tiny_skia/iced_wgpu::text::Pipeline structs.

Since I'm brand new to this code base it's not obvious to me how the font database should be shared between the text pipeline and the svg pipeline, but it seems like it should. I'll poke around some more and see if I can work it out but I'd love guidance if anyone has some.

**Comment by alec-deason** [comment]
I updated the PR with a possible approach to sharing the font database across systems. It feels like it has some ugliness in how the database references get passed around but it works. I'd still love anyone's thoughts on how best to handle this.
